GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJhc2lhcCIsImVtYWlsIjoiYXNpYXBAZ21haWwuY29tIiwiaWF0IjoxNjY1NjYzNTQxLCJleHAiOjE2NjU2NjM1NjF9.EPgJ-jqEPvxhnAjEpqp6msjzql-8-dTn1Y0MYXYnkYs


###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name" : "asiap",
  "email": "asiap@gmail.com",
  "password": "1234",
  "confPassword": "1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "asiap@gmail.com",
  "password": "1234"
}